version: '3'
services:
  php-environment:
    container_name: php-apacheGemberTuin
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./php:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: dbGemberTuin
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: headDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456789
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadminGemberTuin
    links:
      - db
    environment:
      PMA_HOST: db
    restart: always
    ports:
      - 8081:80